# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14AbAlwFgINZCjHDKlGlriYrMDCtPnRu0
"""

!pip install -q gradio transformers torch black autopep8 reportlab requests

import gradio as gr
from datetime import datetime
from pathlib import Path
import json
import sqlite3
import re
import requests
import urllib.parse

schema = {
    "users": ["id","name","email","signup_date","age","country","status"],
    "orders": ["id","user_id","product_name","amount","order_date","status"],
    "products": ["id","name","price","category","stock"],
    "transactions": ["id","user_id","amount","date","type"]
}

def get_table_name(query):
    query = query.lower()

    if "user" in query:
        return "users"
    elif "order" in query:
        return "orders"
    elif "product" in query:
        return "products"
    elif "transaction" in query:
        return "transactions"
    else:
        return "users"

def generate_sql(query):

    table = get_table_name(query)

    sql = f"SELECT * FROM {table} LIMIT 10"

    return sql

def chatbot(user_input):

    sql = generate_sql(user_input)

    return "Generated SQL Query:\n" + sql

demo = gr.Interface(
    fn=chatbot,
    inputs="text",
    outputs="text",
    title="SQL Query Generator"
)

demo.launch()